---
version: '2'

services: 
    proxy:
        build: proxy
        image: nginx_proxy:latest
        networks:
          etcd_net:
            ipv4_address: 172.16.238.20
        volumes:
            - /var/log/nginx:/var/log/nginx
networks:
  etcd_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
