[template]
prefix = "{prefix}"
src = "{src}"
dest = "{dest}"
owner = "root"
mode = "0666"
keys = [
    "/",  				# watch key
]

check_cmd = "nginx -t -c /etc/nginx/nginx.conf"  	#检测到变化后的测试
reload_cmd = "nginx -s reload"       	#配置文件没问题后的reload
